# Generated by Django 5.2.17 on 2026-08-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='accounts.account')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['account', 'completed'], name='todos_todo_account_914a5e_idx'), models.Index(fields=['account', 'created_at'], name='todos_todo_account_9a9c1f_idx')],
            },
        ),
    ]
